#pragma once
#include "afxwin.h"
#include <vector>
#include "stdafx.h"
#include "Othello.h"
#include "OthelloHistory.h"
#include "afxdialogex.h"
#include "AIController.h"
#include "OthelloDlg.h"
#include "Controller.h"
